version: '2'

services:
  mongo: 
    image: mongo 
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: always
  web: #name of your service
    build: ./ 
    ports:
      - "3000:3000" 
    links:
      - mongo
    volumes:
      - ./:/app
    depends_on:
      - mongo
    command: nodemon /app/server.js
